import { v4 as uuidv4 } from 'uuid';

import { log } from 'core/src/helpers/logger';
import { LLMRouter } from 'core/src/llm/router';
import { systemPromptPersonaContext } from 'core/src/personas/llm/systemprompt/systemPromptsPersonaContext';
import { ideasResponseSchema } from 'core/src/reports/llm/controllers/report-type-ideas/schemaIdeasResponse';
import { systemPromptPersonaIdeasResponse } from 'core/src/reports/llm/controllers/report-type-ideas/systemPromptsReportTypeIdeas';

import type { IdeasPersonaResponse } from './schemaIdeasResponse';
import type { ProviderId } from 'core/src/llm/config';
import type { Persona } from 'core/src/personas/persona.types';

const PROVIDER: ProviderId = 'google';
const MODEL = 'gemini-3-flash-preview';

/**
 * Default configuration values
 */
const DEFAULT_MAX_RETRIES = 2;

/**
 * Validate response size and JSON structure
 */
function validateResponse(text: string, maxSize: number): void {
  if (text.length > maxSize) {
    throw new Error(`Response too large: ${text.length} characters (max: ${maxSize})`);
  }

  // Basic JSON validation
  try {
    JSON.parse(text);
  } catch (error) {
    throw new Error(
      `Invalid JSON response: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}

/**
 * Sleep for specified milliseconds
 */
function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Get ideas generated by a persona
 */
export async function getPersonaIdeasResponse(
  persona: Persona,
  prompt: string,
  files?: { data: string; mimeType: string; name?: string }[]
): Promise<IdeasPersonaResponse> {
  const maxResponseSize = 200000; // 200KB max response
  const maxRetries = DEFAULT_MAX_RETRIES;

  // Use the existing persona content if available, otherwise fall back to metadata
  const personaContent = systemPromptPersonaContext(persona, false);

  const systemPrompt = systemPromptPersonaIdeasResponse(personaContent);

  const userPrompt = `Generate ideas based on this request: ${prompt}

Generate multiple concrete, specific ideas that would appeal to people like you. Each idea should reflect your values, preferences, and background.`;

  // Create fallback response function
  const createFallbackResponse = (reason: string): IdeasPersonaResponse => ({
    ideas: [
      {
        idea: 'Unable to generate ideas at this time.',
        reasoning: `I had trouble coming up with ideas. (${reason})`,
        appeal_score: 5,
      },
    ],
  });

  // Retry logic with exponential backoff
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      // Clean prompts to remove emojis and other symbols, but preserve punctuation
      const safeRegex = /[^a-zA-Z0-9\s.,!?'":;()-]/g;
      const cleanedSystemPrompt = systemPrompt.replace(safeRegex, '');
      const cleanedUserPrompt = userPrompt.replace(safeRegex, '');

      const response = await LLMRouter.generate<IdeasPersonaResponse>(PROVIDER, {
        messages: [
          {
            id: uuidv4(),
            role: 'user',
            content: cleanedUserPrompt,
            timestamp: new Date().toISOString(),
          },
        ],
        systemMessage: {
          id: uuidv4(),
          role: 'system',
          content: cleanedSystemPrompt,
          timestamp: new Date().toISOString(),
        },
        files,
        responseFormat: ideasResponseSchema,
        model: MODEL,
      });

      const text = response.text;

      // Validate response before processing
      validateResponse(text, maxResponseSize);

      if (!response.data) {
        throw new Error('Expected structured response but got none');
      }

      const parsedResponse = response.data;

      // Validate required fields
      if (
        !parsedResponse.ideas ||
        !Array.isArray(parsedResponse.ideas) ||
        parsedResponse.ideas.length === 0
      ) {
        throw new Error('Ideas response missing required fields: ideas array');
      }

      // Validate appeal scores are in range
      for (const idea of parsedResponse.ideas) {
        if (idea.appeal_score < 1 || idea.appeal_score > 10) {
          throw new Error(`Appeal score ${idea.appeal_score} is out of range (1-10)`);
        }
      }

      return parsedResponse;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      log.error(
        'REPORTS',
        `Persona ${persona.id} ideas - Attempt ${attempt + 1} failed:`,
        errorMessage
      );

      // If this is the last attempt, return fallback
      if (attempt === maxRetries) {
        log.error(
          'REPORTS',
          `Persona ${persona.id} ideas - All attempts failed, returning fallback response`
        );
        return createFallbackResponse(`All ${maxRetries + 1} attempts failed: ${errorMessage}`);
      }

      // Exponential backoff: wait before retrying
      const backoffTime = Math.min(1000 * Math.pow(2, attempt), 10000); // Max 10 seconds
      await sleep(backoffTime);
    }
  }

  // This should never be reached, but TypeScript requires it
  return createFallbackResponse('Unexpected error in retry logic');
}
