import { v4 as uuidv4 } from 'uuid';

import { log } from 'core/src/helpers/logger';
import { LLMRouter, clearProviderCache } from 'core/src/llm/router';
import { ideasReportSchema } from 'core/src/reports/llm/controllers/report-type-ideas/schemaReportIdeas';
import { systemPromptIdeasReport } from 'core/src/reports/llm/controllers/report-type-ideas/systemPromptsReportTypeIdeas';

import type { ProviderId } from 'core/src/llm/config';
import type { IdeaItem, ReportIdeas } from 'core/src/reports/reports.types';

/**
 * Intermediate type for LLM response - contains idea_ids instead of expanded ideas
 */
type IdeasReportLLMResponse = Omit<ReportIdeas, 'idea_categories' | 'top_ideas'> & {
  idea_categories?: Array<{
    category: string;
    idea_ids: string[];
    percentage: number;
  }>;
  top_ideas?: string[]; // Array of idea IDs
};

/**
 * LLM configuration
 */
const PROVIDER: ProviderId = 'google';
const REPORT_GENERATION_MODEL = 'gemini-2.5-pro';

/**
 * Default configuration values
 */
const DEFAULT_MAX_RETRIES = 2;

/**
 * Validate response size and JSON structure
 * Note: Ideas reports may have legitimate repetition since we're passing through all ideas
 */
function validateResponse(text: string, maxSize: number): void {
  if (text.length > maxSize) {
    throw new Error(`Response too large: ${text.length} characters (max: ${maxSize})`);
  }

  // Check for obvious signs of looping or malformed content
  // Use a higher threshold for ideas reports since we're passing through all ideas
  const repetitionThreshold = 0.7; // Increased from 0.5 to allow for idea data repetition
  const lines = text.split('\n').filter(line => line.trim().length > 0); // Filter empty lines
  if (lines.length === 0) {
    throw new Error('Response appears to be empty');
  }

  const uniqueLines = new Set(lines);
  const repetitionRatio = 1 - uniqueLines.size / lines.length;

  // Only check for extreme repetition (looping)
  if (repetitionRatio > repetitionThreshold && lines.length > 10) {
    throw new Error(
      `Response appears to contain excessive repetition (${Math.round(repetitionRatio * 100)}%)`
    );
  }

  // Basic JSON validation
  try {
    JSON.parse(text);
  } catch (error) {
    throw new Error(
      `Invalid JSON response: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}

/**
 * Sleep for specified milliseconds
 */
function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Generate a comprehensive report from all persona-generated ideas
 */
export async function generateIdeasReport(
  prompt: string,
  allIdeas: IdeaItem[]
): Promise<ReportIdeas> {
  // Clear provider cache to ensure fresh instance with current environment variables
  clearProviderCache();
  const maxResponseSize = 500000; // 500KB max response
  const maxRetries = DEFAULT_MAX_RETRIES;

  const responseFormat = ideasReportSchema;
  const systemPrompt = systemPromptIdeasReport();

  const userPrompt = `Original request: "${prompt}"

Generated ideas from personas:
${allIdeas
  .map(
    (idea, idx) =>
      `${idx + 1}. "${idea.idea}" - Generated by ${idea.persona_name} (${idea.persona_age}, ${idea.persona_occupation}) [Appeal Score: ${idea.appeal_score}/10]\n   Reasoning: ${idea.reasoning}`
  )
  .join('\n\n')}

Please analyze these ideas and generate a comprehensive ideas report.`;

  // Retry logic with exponential backoff
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      // Clean prompts to remove emojis and other symbols, but preserve punctuation
      const safeRegex = /[^a-zA-Z0-9\s.,!?'":;()-]/g;
      const cleanedSystemPrompt = systemPrompt.replace(safeRegex, '');
      const cleanedUserPrompt = userPrompt.replace(safeRegex, '');

      const response = await LLMRouter.generate<IdeasReportLLMResponse>(PROVIDER, {
        messages: [
          {
            id: uuidv4(),
            role: 'user',
            content: cleanedUserPrompt,
            timestamp: new Date().toISOString(),
          },
        ],
        systemMessage: {
          id: uuidv4(),
          role: 'system',
          content: cleanedSystemPrompt,
          timestamp: new Date().toISOString(),
        },
        responseFormat,
        model: REPORT_GENERATION_MODEL,
      });

      const text = response.text;

      // Validate response before processing
      validateResponse(text, maxResponseSize);

      if (!response.data) {
        throw new Error('Expected structured response but got none');
      }

      const parsedResponse = response.data;

      // Validate required fields for report
      if (!parsedResponse.summary) {
        throw new Error('Ideas report response missing required field: summary');
      }

      // Use input ideas as source of truth - ensure all have IDs
      // The LLM may or may not include ideas array, but we always use input ideas
      const ideaIdMap = new Map(allIdeas.map(idea => [idea.id, idea]));
      const ideasWithIds = allIdeas.map((idea, idx) => ({
        ...idea,
        id: idea.id || `idea-${idx + 1}`,
      }));

      // Expand idea_categories from IDs to full objects
      let expandedCategories:
        | Array<{ category: string; ideas: IdeaItem[]; percentage: number }>
        | undefined;
      if (parsedResponse.idea_categories && Array.isArray(parsedResponse.idea_categories)) {
        expandedCategories = parsedResponse.idea_categories
          .map(cat => {
            const categoryIdeas = (cat.idea_ids || [])
              .map(id => ideaIdMap.get(id))
              .filter((idea): idea is IdeaItem => idea !== undefined);
            return {
              category: cat.category,
              ideas: categoryIdeas,
              percentage: cat.percentage,
            };
          })
          .filter(cat => cat.ideas.length > 0); // Only include categories with valid ideas
      }

      // Expand top_ideas from IDs to full objects
      let expandedTopIdeas: IdeaItem[] | undefined;
      if (parsedResponse.top_ideas && Array.isArray(parsedResponse.top_ideas)) {
        expandedTopIdeas = parsedResponse.top_ideas
          .map(id => (typeof id === 'string' ? ideaIdMap.get(id) : null))
          .filter((idea): idea is IdeaItem => idea !== undefined);
      }

      return {
        ...parsedResponse,
        ideas: ideasWithIds, // Use input ideas as source of truth
        idea_categories: expandedCategories,
        top_ideas: expandedTopIdeas,
      };
    } catch (error) {
      let errorMessage = error instanceof Error ? error.message : 'Unknown error';

      log.error(
        'REPORTS',
        `Ideas report generation - Attempt ${attempt + 1} failed:`,
        errorMessage
      );

      // If this is the last attempt, throw the error
      if (attempt === maxRetries) {
        log.error('REPORTS', 'Ideas report generation - All attempts failed');
        throw new Error(
          `Failed to generate ideas report after ${maxRetries + 1} attempts: ${errorMessage}`
        );
      }

      // Exponential backoff: wait before retrying
      const backoffTime = Math.min(1000 * Math.pow(2, attempt), 10000); // Max 10 seconds
      await sleep(backoffTime);
    }
  }

  // This should never be reached, but TypeScript requires it
  throw new Error('Unexpected error in ideas report generation retry logic');
}
