import { z } from 'zod';

import { createSchemaDefinition, type SchemaDefinition } from 'core/src/llm/schemas/schema';

export type IdeasPersonaResponse = {
  ideas: Array<{
    idea: string;
    reasoning: string;
    appeal_score: number; // 1-10 how appealing this idea is to this persona
  }>;
};

const ideaItemSchemaZod = z.object({
  idea: z
    .string()
    .describe(
      'The specific idea generated (e.g., a startup name, ad concept, product feature, etc.). Should be concrete and specific.'
    ),
  reasoning: z
    .string()
    .describe(
      'Explanation of why this persona thinks this idea would appeal to people like them. Should reflect their values, preferences, and background.'
    ),
  appeal_score: z
    .number()
    .min(1)
    .max(10)
    .describe(
      'How appealing this idea is to this persona on a scale of 1-10, where 10 is extremely appealing.'
    ),
});

export const ideasResponseSchemaZod = z
  .object({
    ideas: z
      .array(ideaItemSchemaZod)
      .min(1)
      .describe(
        'An array of ideas generated by this persona. Each persona should generate multiple ideas (typically 3-10 depending on the request).'
      ),
  })
  .describe(
    'Response format for persona generating ideas that would appeal to their demographic/psychographic profile.'
  );

export const ideasResponseSchema: SchemaDefinition = createSchemaDefinition(
  ideasResponseSchemaZod,
  {
    name: 'ideas_response',
    strict: true,
  }
);
