import type { ModelMap } from 'core/src/llm/provider.types';

export const googleModels: ModelMap = {
  'gemini-2.5-flash': {
    name: 'Gemini 2.5 Flash',
    attachment: true,
    reasoning: true,
    temperature: true,
    tool_call: true,
    knowledge: '2025-01',
    release_date: '2025-03-20',
    last_updated: '2025-06-05',
    modalities: {
      input: ['text', 'image', 'audio', 'video', 'pdf'],
      output: ['text'],
    },
    open_weights: false,
    limit: { context: 1048576, output: 65536 },
    enabled: true,
  },
  'gemini-2.5-flash-preview-09-2025': {
    name: 'Gemini 2.5 Flash Preview 2025 09',
    attachment: true,
    reasoning: true,
    temperature: true,
    tool_call: true,
    knowledge: '2025-01',
    release_date: '2025-09-25',
    last_updated: '2025-09-25',
    modalities: {
      input: ['text', 'image', 'audio', 'video', 'pdf'],
      output: ['text'],
    },
    open_weights: false,
    limit: { context: 1048576, output: 65536 },
    enabled: false,
  },
  'gemini-2.5-flash-lite': {
    name: 'Gemini 2.5 Flash Lite',
    attachment: true,
    reasoning: true,
    temperature: true,
    tool_call: true,
    knowledge: '2025-01',
    release_date: '2025-06-17',
    last_updated: '2025-06-17',
    modalities: {
      input: ['text', 'image', 'audio', 'video', 'pdf'],
      output: ['text'],
    },
    open_weights: false,
    limit: { context: 65536, output: 65536 },
    enabled: true,
  },
  'gemini-2.5-flash-lite-preview-06-17': {
    name: 'Gemini 2.5 Flash Lite Preview 06-17',
    shortName: 'Gemini 2.5 Flash Lite',
    attachment: true,
    reasoning: true,
    temperature: true,
    tool_call: true,
    knowledge: '2025-01',
    release_date: '2025-06-17',
    last_updated: '2025-06-17',
    modalities: {
      input: ['text', 'image', 'audio', 'video', 'pdf'],
      output: ['text'],
    },
    open_weights: false,
    limit: { context: 65536, output: 65536 },
    enabled: false,
  },
  'gemini-2.5-pro': {
    name: 'Gemini 2.5 Pro',
    attachment: true,
    reasoning: true,
    temperature: true,
    tool_call: true,
    knowledge: '2025-01',
    release_date: '2025-03-20',
    last_updated: '2025-06-05',
    modalities: {
      input: ['text', 'image', 'audio', 'video', 'pdf'],
      output: ['text'],
    },
    open_weights: false,
    limit: { context: 1048576, output: 65536 },
    enabled: true,
  },
  'gemini-3-pro-preview': {
    name: 'Gemini 3 Pro',
    attachment: true,
    reasoning: true,
    temperature: true,
    tool_call: true,
    knowledge: '2025-01',
    release_date: '2025-01-01',
    last_updated: '2025-01-01',
    modalities: {
      input: ['text', 'image', 'audio', 'video', 'pdf'],
      output: ['text'],
    },
    open_weights: false,
    limit: { context: 200000, output: 65536 },
    enabled: true,
  },
  'gemini-3-flash-preview': {
    name: 'Gemini 3 Flash',
    attachment: true,
    reasoning: true,
    temperature: true,
    tool_call: true,
    knowledge: '2025-01',
    release_date: '2025-12-17',
    last_updated: '2025-12-17',
    modalities: {
      input: ['text', 'image', 'audio', 'video', 'pdf'],
      output: ['text'],
    },
    open_weights: false,
    limit: { context: 1048576, output: 65536 },
    enabled: true,
  },
  'gemini-3.1-pro-preview': {
    name: 'Gemini 3.1 Pro',
    attachment: true,
    reasoning: true,
    temperature: true,
    tool_call: true,
    knowledge: '2025-01',
    release_date: '2025-12-17',
    last_updated: '2025-12-17',
    modalities: {
      input: ['text', 'image', 'audio', 'video', 'pdf'],
      output: ['text'],
    },
    open_weights: false,
    limit: { context: 1048576, output: 65536 },
    enabled: true,
  },
  'gemini-3.1-flash-lite-preview': {
    name: 'Gemini 3.1 Flash Lite',
    attachment: true,
    reasoning: true,
    temperature: true,
    tool_call: true,
    knowledge: '2025-01',
    release_date: '2025-12-17',
    last_updated: '2025-12-17',
    modalities: {
      input: ['text', 'image', 'audio', 'video', 'pdf'],
      output: ['text'],
    },
    open_weights: false,
    limit: { context: 1048576, output: 65536 },
    enabled: true,
  },
};
