export const GENDER_OPTIONS = [
  'woman',
  'man',
  'nonbinary',
  'genderfluid',
  'agender',
  'demigender',
  'bigender',
  'pangender',
  'other',
  'prefer not to say',
] as const;

export const GENDER_IDENTITY_STATUS_OPTIONS = ['transgender', 'prefer not to say'] as const;

export const SEXUAL_ORIENTATION_OPTIONS = [
  'heterosexual',
  'homosexual',
  'bisexual',
  'asexual',
  'pansexual',
  'demisexual',
  'queer',
  'questioning',
  'prefer not to say',
] as const;

export const PRONOUNS_OPTIONS = [
  'she/her',
  'he/him',
  'they/them',
  'she/they',
  'he/they',
  'they/she',
  'they/he',
  'ze/zir',
  'name only',
  'prefer not to say',
] as const;

export const LOCATION_OPTIONS = [
  'United Kingdom',
  'United States',
  'Canada',
  'Australia',
  'New Zealand',
  'France',
  'India',
  'China',
  'Brazil',
  'Turkey',
  'Other',
] as const;

export const ETHNICITY_OPTIONS = [
  'White',
  'Black',
  'Hispanic',
  'Latino',
  'East Asian',
  'South Asian',
  'Southeast Asian',
  'Middle Eastern',
  'North African',
  'Native American',
  'Indigenous American',
  'Pacific Islander',
  'Native Hawaiian',
  'Indigenous Australian',
  'Torres Strait Islander',
  'Sub-Saharan African',
  'Caribbean',
  'Mixed',
  'Multiracial',
  'Other',
  'Prefer not to say',
] as const;

export const LANGUAGES_OPTIONS = [
  'English',
  'French',
  'Spanish',
  'German',
  'Italian',
  'Portuguese',
  'Arabic',
] as const;

export const JOB_INFORMATION_OPTIONS = [
  'Technology',
  'Education',
  'Healthcare',
  'Finance',
  'Legal',
  'Government',
  'Nonprofit',
  'Retail',
  'Hospitality',
  'Construction',
  'Manufacturing',
  'Transportation',
  'Media & Entertainment',
  'Marketing & Advertising',
  'Science & Research',
  'Engineering',
  'Real Estate',
  'Arts & Design',
  'Agriculture',
  'Telecommunications',
  'Energy & Utilities',
  'Human Resources',
  'Business Services',
  'Sports & Recreation',
  'Military',
  'Student',
  'Unemployed',
  'Retired',
  'Other',
] as const;

export const EDUCATION_OPTIONS = [
  'No formal education',
  'Primary education',
  'Secondary education',
  'High school diploma or equivalent',
  'Some college or university',
  'Vocational or technical training',
  'Associate degree',
  'Bachelor’s degree',
  'Master’s degree',
  'Professional degree (e.g., JD, MD)',
  'Doctorate (PhD or equivalent)',
  'Currently enrolled',
  'Prefer not to say',
] as const;

export const PERSONALITY_TRAITS = [
  'curious',
  'imaginative',
  'analytical',
  'creative',
  'intuitive',
  'observant',
  'insightful',
  'open-minded',
  'resourceful',
  'philosophical',
  'thoughtful',
  'empathetic',
  'kind',
  'sensitive',
  'affectionate',
  'romantic',
  'gentle',
  'loyal',
  'compassionate',
  'emotionally intelligent',
  'resilient',
  'brave',
  'grounded',
  'independent',
  'determined',
  'adaptable',
  'confident',
  'disciplined',
  'calm under pressure',
  'mentally tough',
  'adventurous',
  'outgoing',
  'witty',
  'charming',
  'funny',
  'charismatic',
  'friendly',
  'spontaneous',
  'diplomatic',
  'easygoing',
  'authentic',
  'ambitious',
  'driven',
  'principled',
  'playful',
  'humble',
  'generous',
  'curious about others',
  'lives with intention',
  'always learning',
  // Additional traits for more variety
  'perfectionist',
  'impatient',
  'stubborn',
  'pessimistic',
  'cynical',
  'skeptical',
  'competitive',
  'controlling',
  'moody',
  'anxious',
  'introverted',
  'reserved',
  'cautious',
  'traditional',
  'detail-oriented',
  'big-picture thinker',
  'methodical',
  'systematic',
  'flexible',
  'decisive',
  'indecisive',
  'energetic',
  'laid-back',
  'intense',
  'mellow',
  'focused',
  'scattered',
  'persistent',
  'easily distracted',
  'logical',
  'emotional',
  'practical',
  'idealistic',
  'introspective',
  'strategic',
  'realistic',
  'optimistic',
  'collaborative',
  'team-oriented',
  'caring',
  'passionate',
  'skilled',
  'wise',
  'unpredictable',
  // Social positioning
  'dominant',
  'submissive',
  'assertive',
  'passive',
  'aggressive',
  'passive-aggressive',
  'confrontational',
  'avoidant',
  'people-pleasing',
  'boundary-setting',
  // Communication & social styles
  'direct',
  'indirect',
  'blunt',
  'tactful',
  'sarcastic',
  'sincere',
  'manipulative',
  'transparent',
  'secretive',
  'oversharing',
  // Emotional regulation & expression
  'volatile',
  'stable',
  'dramatic',
  'understated',
  'expressive',
  'stoic',
  'jealous',
  'trusting',
  'suspicious',
  'naive',
  // Risk & novelty
  'risk-averse',
  'thrill-seeking',
  'conservative',
  'rebellious',
  'conformist',
  'nonconformist',
  'conventional',
  'eccentric',
  // Work & achievement styles
  'workaholic',
  'procrastinator',
  'overachiever',
  'underachiever',
  'meticulous',
  'careless',
  'reliable',
  'flaky',
  'punctual',
  'chronically late',
  // Social energy & preferences
  'extroverted',
  'socially anxious',
  'attention-seeking',
  'self-effacing',
  'gregarious',
  'solitary',
  'networker',
  'hermit-like',
  // Cognitive & learning styles
  'quick-witted',
  'slow-processing',
  'intuitive-leaper',
  'step-by-step thinker',
  'abstract',
  'concrete',
  'theoretical',
  'hands-on',
  // Moral & ethical orientations
  'rule-following',
  'rule-bending',
  'morally rigid',
  'morally flexible',
  'judgmental',
  'non-judgmental',
  'self-righteous',
  'self-critical',
  // Relationship & attachment styles
  'clingy',
  'aloof',
  'codependent',
  'fiercely independent',
  'commitment-phobic',
  'relationship-focused',
  'emotionally unavailable',
  'emotionally needy',
  // Additional complex traits
  'protective',
  'insecure',
  'defensive',
  'lonely',
  'resentful',
  'honest',
  'apologetic',
  'well-meaning',
  'contradictory',
  'overcompensating',
  'vulnerable',
  'experienced',
  'hopeful',
  'overcommitted',
  'brilliant',
] as const;

export const RELATIONSHIP_STATUS_OPTIONS = [
  'single',
  'in a relationship',
  'married',
  'engaged',
  'divorced',
  'widowed',
  'separated',
  'polyamorous',
  "it's complicated",
  'open relationship',
  'situationship',
  'prefer not to say',
] as const;

export const POLITICAL_LEANING_OPTIONS = [
  'Progressive',
  'Liberal',
  'Moderate-Liberal',
  'Centrist',
  'Moderate-Conservative',
  'Conservative',
  'Libertarian',
  'Green',
  'Socialist',
  'Independent',
  'Apolitical',
  'Populist',
] as const;

export const ZODIAC_SIGN_OPTIONS = [
  'Aries',
  'Taurus',
  'Gemini',
  'Cancer',
  'Leo',
  'Virgo',
  'Libra',
  'Scorpio',
  'Sagittarius',
  'Capricorn',
  'Aquarius',
  'Pisces',
] as const;

// Height ranges in centimeters (realistic adult heights)
export const HEIGHT_RANGES = {
  // Very short
  VERY_SHORT: [140, 155] as const,
  // Short
  SHORT: [155, 165] as const,
  // Average
  AVERAGE: [165, 180] as const,
  // Tall
  TALL: [180, 195] as const,
  // Very tall
  VERY_TALL: [195, 210] as const,
} as const;

// Generation age groups (ages as of 2025)
export const GENERATIONS = [
  { name: 'Generation Alpha', minAge: 0, maxAge: 12, born: '2013-2025' },
  { name: 'Generation Z', minAge: 13, maxAge: 28, born: '1997-2012' },
  { name: 'Millennial', minAge: 29, maxAge: 44, born: '1981-1996' },
  { name: 'Generation X', minAge: 45, maxAge: 60, born: '1965-1980' },
  { name: 'Baby Boomer', minAge: 61, maxAge: 79, born: '1946-1964' },
  { name: 'Silent Generation', minAge: 80, maxAge: 97, born: '1928-1945' },
];
